more attempts at fixing

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -154,95 +154,97 @@ jobs:
           echo $PATH
           which glslc
           glslc --version
-          ./src/Griddly/Core/Observers/Vulkan/resources/shaders/compile_shaders.sh
-          cmake . -DCMAKE_BUILD_TYPE=Debug
+          cd src/Griddly/Core/Observers/Vulkan/resources/shaders/
+          compile_shaders.sh
+          cd -
+          # cmake . -DCMAKE_BUILD_TYPE=Debug
           ls resources
           ls resources/shaders
-          cmake --build . --target Griddly_Test
+          # cmake --build . --target Griddly_Test
         displayName: Build
-      - bash: |
-          export PATH=$PATH:/c/VulkanSDK/1.2.148.0/Bin
-          export GTEST_FILTER=-*BlockObserverTest*:*SpriteObserverTest*
-          export GTEST_OUTPUT=xml:test-report.xml
-          ctest . -C Debug 
-        continueOnError: true
-        displayName: Test
-      - task: PublishTestResults@2
-        inputs:
-          failTaskOnFailedTests: true
-          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
-          testResultsFiles: test-report.xml
-          testRunTitle: Windows Tests
-        displayName: Publish Test Results
+      # - bash: |
+      #     export PATH=$PATH:/c/VulkanSDK/1.2.148.0/Bin
+      #     export GTEST_FILTER=-*BlockObserverTest*:*SpriteObserverTest*
+      #     export GTEST_OUTPUT=xml:test-report.xml
+      #     ctest . -C Debug 
+      #   continueOnError: true
+      #   displayName: Test
+      # - task: PublishTestResults@2
+      #   inputs:
+      #     failTaskOnFailedTests: true
+      #     testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
+      #     testResultsFiles: test-report.xml
+      #     testRunTitle: Windows Tests
+      #   displayName: Publish Test Results
 
-  - job: PyPiDeployWindows
-    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'test_deploy')))
-    dependsOn: Windows
-    variables:
-      VULKAN_SDK: C:/VulkanSDK/1.2.148.0
-    timeoutInMinutes: 20
-    pool:
-      vmImage: "windows-latest"
-    strategy:
-      matrix:
-        Windows_p36:
-          PythonVersion: 3.6
-        Windows_p37:
-          PythonVersion: 3.7
-        Windows_p38:
-          PythonVersion: 3.8
-    steps:
-      - task: InstallSSHKey@0
-        inputs:
-          knownHostsEntry: $(griddly_known_hosts_entry)
-          sshPublicKey: $(griddly_azure_public_key)
-          sshPassphrase: $(griddly_azure_passphrase)
-          sshKeySecureFile: griddly
-      - checkout: self
-        submodules: true
-        persistCredentials: true
-      - task: UsePythonVersion@0
-        inputs:
-          versionSpec: $(PythonVersion)
-          addToPath: true 
-        displayName: Set Python $(PythonVersion)
-      - bash: |
-          set -ex
-          curl -L -o "vulkan-installer.exe" "https://griddyvulkan.s3.amazonaws.com/VulkanSDK-1.2.148.0-Installer.exe"
-          # This makes sure we wait for the vulkan SDK to complete installation
-          _=$(echo "vulkan-installer.exe /S" | cmd)
-          curl -L -o "vulkan-runtime.zip" "https://griddyvulkan.s3.amazonaws.com/vulkan-1.2.148.0-runtime-components.zip"
-          unzip vulkan-runtime.zip
-          cp VulkanRT-1.2.148.0-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
-          cp VulkanRT-1.2.148.0-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
-        displayName: Installing Vulkan
-      - bash: |
-          set -ex
-          export PATH=$PATH:/c/VulkanSDK/1.2.148.0/Bin
-          echo $PATH
-          cmake . -DCMAKE_BUILD_TYPE=Release
-          cmake --build . --target python_griddly --config Release
-        displayName: Build
-      - script: |
-          cd python
-          pip install wheel setuptools
-          python setup.py bdist_wheel
-        displayName: Build Wheels
-      - task: TwineAuthenticate@1
-        displayName: "Twine Authenticate (test)"
-        inputs:
-          pythonUploadServiceConnection: pypitest
-        condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'test_deploy'))
-      - task: TwineAuthenticate@1
-        displayName: "Twine Authenticate (live)"
-        inputs:
-          pythonUploadServiceConnection: pypilive
-        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
-      - script: |
-          pip install twine
-          cd python
-          python -m twine upload -r "griddly" --config-file $(PYPIRC_PATH) dist/*.whl
-        displayName: Deploy To PyPi
+  # - job: PyPiDeployWindows
+  #   condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'test_deploy')))
+  #   dependsOn: Windows
+  #   variables:
+  #     VULKAN_SDK: C:/VulkanSDK/1.2.148.0
+  #   timeoutInMinutes: 20
+  #   pool:
+  #     vmImage: "windows-latest"
+  #   strategy:
+  #     matrix:
+  #       Windows_p36:
+  #         PythonVersion: 3.6
+  #       Windows_p37:
+  #         PythonVersion: 3.7
+  #       Windows_p38:
+  #         PythonVersion: 3.8
+  #   steps:
+  #     - task: InstallSSHKey@0
+  #       inputs:
+  #         knownHostsEntry: $(griddly_known_hosts_entry)
+  #         sshPublicKey: $(griddly_azure_public_key)
+  #         sshPassphrase: $(griddly_azure_passphrase)
+  #         sshKeySecureFile: griddly
+  #     - checkout: self
+  #       submodules: true
+  #       persistCredentials: true
+  #     - task: UsePythonVersion@0
+  #       inputs:
+  #         versionSpec: $(PythonVersion)
+  #         addToPath: true 
+  #       displayName: Set Python $(PythonVersion)
+  #     - bash: |
+  #         set -ex
+  #         curl -L -o "vulkan-installer.exe" "https://griddyvulkan.s3.amazonaws.com/VulkanSDK-1.2.148.0-Installer.exe"
+  #         # This makes sure we wait for the vulkan SDK to complete installation
+  #         _=$(echo "vulkan-installer.exe /S" | cmd)
+  #         curl -L -o "vulkan-runtime.zip" "https://griddyvulkan.s3.amazonaws.com/vulkan-1.2.148.0-runtime-components.zip"
+  #         unzip vulkan-runtime.zip
+  #         cp VulkanRT-1.2.148.0-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
+  #         cp VulkanRT-1.2.148.0-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
+  #       displayName: Installing Vulkan
+  #     - bash: |
+  #         set -ex
+  #         export PATH=$PATH:/c/VulkanSDK/1.2.148.0/Bin
+  #         echo $PATH
+  #         cmake . -DCMAKE_BUILD_TYPE=Release
+  #         cmake --build . --target python_griddly --config Release
+  #       displayName: Build
+  #     - script: |
+  #         cd python
+  #         pip install wheel setuptools
+  #         python setup.py bdist_wheel
+  #       displayName: Build Wheels
+  #     - task: TwineAuthenticate@1
+  #       displayName: "Twine Authenticate (test)"
+  #       inputs:
+  #         pythonUploadServiceConnection: pypitest
+  #       condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'test_deploy'))
+  #     - task: TwineAuthenticate@1
+  #       displayName: "Twine Authenticate (live)"
+  #       inputs:
+  #         pythonUploadServiceConnection: pypilive
+  #       condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+  #     - script: |
+  #         pip install twine
+  #         cd python
+  #         python -m twine upload -r "griddly" --config-file $(PYPIRC_PATH) dist/*.whl
+  #       displayName: Deploy To PyPi
 
   # - job: MacOS
   #   timeoutInMinutes: 30
